.bolt/
docs/
src/activities/
src/chat/
src/coding/
src/dashboard/
src/datasets/
src/experiment/
src/fund/
src/layout/
src/literature/
src/patent/
src/projects/
src/shared/
src/team/
src/workspace/
src/pages/ActivityList.tsx
src/pages/ChatPage.tsx
src/pages/Dashboard.tsx
src/pages/LiteraturePage.tsx
src/pages/TaskList.tsx
src/pages/datasets/
src/pages/projects/
src/pages/settings/
src/stores/chatStore.ts
src/stores/projectStore.ts
src/utils/
index.html
.eslint.config.js
.gitignore
package-lock.json
package.json
postcss.config.js
tailwind.config.js
tsconfig.app.json
tsconfig.json
tsconfig.node.json
vite.config.ts